/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

 module.exports = {
    postman: [
      {
        type: 'autogenerated',
        dirName: '.',
      }
      // {
      //   type: 'category',
      //   label: 'Api Doc',
      //   items: [
      //     'OAuth OIDC.postman_collection',
      //     'MQTT.postman_collection',
      //     'GB28181.postman_collection',
      //     'ChatGPT-openapi',
      //     'Camunda-openapi',
      //   ]
      // }
    ],
  };
  