/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

 module.exports = {
    diy: [
      'README',
      'device-and-software-plan',
      {
        type: 'category',
        label: 'Device',
        link: {
          type: 'generated-index',
          title: 'Device',
          description: 'Device',
          keywords: ['device', 'j4125'],
          image: 'img/docusaurus.png'
        },
        items: [
          // {
          //   type: 'autogenerated',
          //   dirName: 'device',
          // },
          'device/j4125',
        ],
      },
      {
        type: 'category',
        label: 'Network',
        link: {
          type: 'generated-index',
          title: 'Network',
          description: 'Network',
          keywords: ['network'],
          image: 'img/docusaurus.png'
        },
        items: [
          // {
          //   type: 'autogenerated',
          //   dirName: 'network',
          // },
          'network/Aliyun-Domain-Config',
          'network/Cloudflare-DDNS-Proxy-IPv4',
          'network/Cloudflare-DDNS-Proxy-IPv6',
          'network/Free-Domain-eu.org',
          'network/Internet-Proxy',
        ],
      },
      {
        type: 'category',
        label: 'Android',
        link: {
          type: 'generated-index',
          title: 'Android',
          description: 'Android',
          keywords: ['android'],
          image: 'img/docusaurus.png'
        },
        items: [
          // {
          //   type: 'autogenerated',
          //   dirName: 'android',
          // },
          'android/Termux',
          'android/Flash-Reference-XiaoMi',
          'android/Flush-Record-Redmi7a',
          'android/Redmi7a-UbuntuTouch',
          'android/Redmi7a-PostmarketOS',
          'android/Redmi7a-Mobian',
          'android/Android-NAS',
        ],
      },
      {
        type: 'category',
        label: 'NAS',
        link: {
          type: 'generated-index',
          title: 'NAS',
          description: 'NAS',
          keywords: ['nas'],
          image: 'img/docusaurus.png'
        },
        items: [
          // {
          //   type: 'autogenerated',
          //   dirName: 'nas',
          // },
          'nas/NAS-Reference',
          'nas/Synology-7.2',
          'nas/Aria2',
          'nas/Opensource-CloudDriver',
        ],
      },
      {
        type: 'category',
        label: 'Home Assistant',
        link: {
          type: 'generated-index',
          title: 'Home Assistant',
          description: 'Home Assistant',
          keywords: ['homeassistant', 'home-assistant', 'ha'],
          image: 'img/docusaurus.png'
        },
        items: [
          // {
          //   type: 'autogenerated',
          //   dirName: 'homeassistant',
          // },
          'homeassistant/Install-HA-Core-With-LinuxDeploy',
        ],
      },
      {
        type: 'category',
        label: 'Router',
        link: {
          type: 'generated-index',
          title: 'Router',
          description: 'Router',
          keywords: ['router'],
          image: 'img/docusaurus.png'
        },
        items: [
          // {
          //   type: 'autogenerated',
          //   dirName: 'router',
          // },
          'router/GM219',
          'router/H2-2',
          'router/H2-2-Router',
        ],
      },
      {
        type: 'category',
        label: 'Soft Router',
        link: {
          type: 'generated-index',
          title: 'Soft Router',
          description: 'Soft Router',
          keywords: ['soft-router'],
          image: 'img/docusaurus.png'
        },
        items: [
          // {
          //   type: 'autogenerated',
          //   dirName: 'soft-router',
          // },
          'soft-router/Install',
          'soft-router/OpenWrt',
          'soft-router/Compile-OpenWrt-with-Github',
          'soft-router/iKuai',
          'soft-router/iStoreOS',
          'soft-router/MikroTik',
          'soft-router/RouterOS',
          'soft-router/PfSense',
          'soft-router/OpnSense',
        ],
      },
      {
        type: 'category',
        label: 'TV Box',
        link: {
          type: 'generated-index',
          title: 'TV Box',
          description: 'TV Box',
          keywords: ['tv-box'],
          image: 'img/docusaurus.png'
        },
        items: [
          // {
          //   type: 'autogenerated',
          //   dirName: 'tv-box',
          // },
          'tv-box/HTPC',
        ],
      },
      {
        type: 'category',
        label: 'Game Box',
        link: {
          type: 'generated-index',
          title: 'Game Box',
          description: 'Game Box',
          keywords: ['game-box'],
          image: 'img/docusaurus.png'
        },
        items: [
          // {
          //   type: 'autogenerated',
          //   dirName: 'game-box',
          // },
          'game-box/TV-Games',
          'game-box/Switch',
          'game-box/PSP',
          'game-box/XBox',
        ],
      },
    ],
  };
  