/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  middleware: [
    'README',
    {
      type: 'category',
      label: 'Compare',
      link: {
        type: 'generated-index',
        title: 'Compare',
        description: 'Compare',
        keywords: ['compare'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'compare',
        },
      ],
    },
    {
      type: 'category',
      label: 'Mysql',
      link: {
        type: 'generated-index',
        title: 'Mysql',
        description: 'Mysql',
        keywords: ['mysql'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'mysql',
        },
      ],
    },
    {
      type: 'category',
      label: 'Postgresql',
      link: {
        type: 'generated-index',
        title: 'Postgresql',
        description: 'Postgresql',
        keywords: ['postgresql', 'pgsql'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'pgsql',
        },
      ],
    },
    {
      type: 'category',
      label: 'Redis',
      link: {
        type: 'generated-index',
        title: 'Redis',
        description: 'Redis',
        keywords: ['redis'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'redis',
        },
      ],
    },
    {
      type: 'category',
      label: 'Nginx',
      link: {
        type: 'generated-index',
        title: 'Nginx',
        description: 'Nginx',
        keywords: ['nginx'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'nginx',
        },
      ],
    },
    {
      type: 'category',
      label: 'Netty',
      link: {
        type: 'generated-index',
        title: 'Netty',
        description: 'Netty',
        keywords: ['netty'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'netty',
        },
      ],
    },
    {
      type: 'category',
      label: 'MQTT',
      link: {
        type: 'generated-index',
        title: 'MQTT',
        description: 'MQTT',
        keywords: ['mqtt', 'emqx', 'mqttx'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'mqtt',
        },
      ],
    },
    {
      type: 'category',
      label: 'InfluxDB',
      link: {
        type: 'generated-index',
        title: 'InfluxDB',
        description: 'InfluxDB',
        keywords: ['influxDB', 'influxdb'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'influxdb',
        },
      ],
    },
    {
      type: 'category',
      label: 'Kafka',
      link: {
        type: 'generated-index',
        title: 'Kafka',
        description: 'Kafka',
        keywords: ['kafka'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'kafka',
        },
      ],
    },
    {
      type: 'category',
      label: 'RabbitMQ',
      link: {
        type: 'generated-index',
        title: 'RabbitMQ',
        description: 'RabbitMQ',
        keywords: ['rabbitmq'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'rabbitmq',
        },
      ],
    },
    {
      type: 'category',
      label: 'RocketMQ',
      link: {
        type: 'generated-index',
        title: 'RocketMQ',
        description: 'RocketMQ',
        keywords: ['rocketmq'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'rocketmq',
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflow',
      link: {
        type: 'generated-index',
        title: 'Workflow',
        description: 'Workflow',
        keywords: ['workflow'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'workflow',
        },
      ],
    },
    {
      type: 'category',
      label: 'Plusar',
      link: {
        type: 'generated-index',
        title: 'Plusar',
        description: 'Plusar',
        keywords: ['plusar'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plusar',
        },
      ],
    },
    {
      type: 'category',
      label: 'ShardingSphere',
      link: {
        type: 'generated-index',
        title: 'ShardingSphere',
        description: 'ShardingSphere',
        keywords: ['shardingsphere'],
        image: 'img/docusaurus.png'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'shardingsphere',
        },
      ],
    },
  ],
};
