services:

  aria2:
    image: p3terx/aria2-pro
    container_name: app_aria2
    hostname: aria2.app
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.180
        aliases:
          - aria2.app
    dns:
      - 192.168.137.1
      - 8.8.8.8
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - aria2.app:172.100.0.180
      - ariang.app:172.100.0.181
      - bitcomet.app:172.100.0.182
      - alist.app:172.100.0.184
      - nextcloud.app:172.100.0.186
    ports:
      - 6888:6888/tcp
      - 6888:6888/udp
    expose:
      - 6800
      - 6888
    volumes:
      - //d/docker/develop/app/aria2/data:/downloads
      - //d/docker/develop/app/aria2/conf:/config
    environment:
      TZ : Asia/Shanghai
      PUID: 1000
      PGID: 1000
      UMASK_SET: '022'
      RPC_PORT: 6800
      LISTEN_PORT: 6888
      RPC_SECRET: lightaria2
      DISK_CACHE: 64M
      IPV6_MODE: false
      UPDATE_TRACKERS: true
      CUSTOM_TRACKER_URL:
    restart: unless-stopped
    # Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m

  # 可以使用Nginx替代
  ariang:
    image: p3terx/ariang
    container_name: app_ariang
    hostname: ariang.app
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.181
        aliases:
          - ariang.app
    dns:
      - 192.168.137.1
      - 8.8.8.8
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - aria2.app:172.100.0.180
      - ariang.app:172.100.0.181
      - bitcomet.app:172.100.0.182
      - alist.app:172.100.0.184
      - nextcloud.app:172.100.0.186
    # ports:
    #   - 6880:6880
    expose:
      - 6880
    command: --port 6880 --ipv6
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

  # http://wiki-zh.bitcomet.com/linux版bitcomet安装指南
  bitcomet:
    image: wxhere/bitcomet:v2.11.0-amd64
    container_name: app_bitcomet
    hostname: bitcomet.app
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.182
        aliases:
          - bitcomet.app
    dns:
      - 192.168.137.1
      - 8.8.8.8
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - aria2.app:172.100.0.180
      - ariang.app:172.100.0.181
      - bitcomet.app:172.100.0.182
      - alist.app:172.100.0.184
      - nextcloud.app:172.100.0.186
    ports:
      - 5900:5900
      - 6082:6082
      - 6082:6082/udp
    expose:
      - 80    # Web GUI 访问端口
      - 5900  # VNC GUI 访问端口
      - 6082  # BitTorrent 端口
    volumes:
      # 将容器中的下载目录映射到主机目录中
      - //d/docker/develop/app/bitcomet/data:/home/sandbox/Downloads:rw
      # 将容器中的配置文件目录映射到主机目录中
      - //d/docker/develop/app/bitcomet/conf:/home/sandbox/.config/BitComet:rw
    environment:
      USER: bitcomet
      PASSWORD: lightbit
      VNC_PASSWORD: lightbit
      HTTP_PASSWORD: lightbit

  alist:
    image: xhofe/alist:v3.40.0
    # image: xiaoyaliu/alist:latest
    container_name: app_alist
    hostname: alist.app
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.184
        aliases:
          - alist.app
    dns:
      - 192.168.137.1
      - 8.8.8.8
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - aria2.app:172.100.0.180
      - ariang.app:172.100.0.181
      - bitcomet.app:172.100.0.182
      - alist.app:172.100.0.184
      - nextcloud.app:172.100.0.186
    # ports:
    #   - 5244:5244
    expose:
      - 5244
    volumes:
      - //d/docker/develop/app/alist/data:/opt/alist/data
    environment:
      TZ: Asia/Shanghai
      PUID: 1000
      PGID: 1000
      UMASK: '022'
    restart: unless-stopped

  nextcloud:
    image: nextcloud:30.0.2-apache
    container_name: app_nextcloud
    hostname: nextcloud.app
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.186
        aliases:
          - nextcloud.app
    dns:
      - 192.168.137.1
      - 8.8.8.8
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - aria2.app:172.100.0.180
      - ariang.app:172.100.0.181
      - bitcomet.app:172.100.0.182
      - alist.app:172.100.0.184
      - nextcloud.app:172.100.0.186
    # ports:
    #   - 80:80
    expose:
      - 80
    volumes:
      - //d/docker/develop/app/nextcloud/data:/var/www/html/data
      # - //d/docker/develop/app/nextcloud/html:/var/www/html
      - //d/docker/develop/app/nextcloud/apps:/var/www/html/custom_apps
      - //d/docker/develop/app/nextcloud/conf:/var/www/html/config
      - //d/docker/develop/app/nextcloud/themes:/var/www/html/themes
    environment:
      - NEXTCLOUD_ADMIN_USER=root
      - NEXTCLOUD_ADMIN_PASSWORD=root
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - NEXTCLOUD_TRUSTED_DOMAINS=172.100.0.186 nextcloud.app nextcloud.light.local
      # Pgsql
      - POSTGRES_HOST=pgsql.basic:5432
      # - POSTGRES_HOST_PORT=5432
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      # Redis
      - REDIS_HOST=redis.basic
      - REDIS_HOST_PORT=6379
      # - REDIS_HOST_PASSWORD=
    restart: no # unless-stopped

networks:
  develop:
    external: true
  proxy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.77.0.0/16

# volumes:
#   aria2_data:
#   bitcomet_data:
