version: "3"

services:
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: web_keycloak
    hostname: keycloak.web
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.170
        aliases:
          - keycloak.web
    dns:
      - 192.168.137.1
      - 8.8.8.8
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - keycloak.web:172.100.0.170
      - minio.web:172.100.0.172
      - gitlab.web:172.100.0.174
      - gitlab-runner.web:172.100.0.175
      - outline.web:172.100.0.176
      - readeck.web:172.100.0.178
    # ports:
    #   - 8080:8080
    expose:
      - 8080
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://pgsql.basic:5432/keycloak
      KC_DB_USER: keycloak
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # 外部访问使用的域名端口信息，与 KC_HOSTNAME_URL 二选一
      # KC_HOSTNAME: keycloak.light.local
      # KC_HOSTNAME_PORT: 443
      
      # 外部访问使用的域名地址，解决初始化403问题
      KC_HOSTNAME_URL: https://keycloak.light.local
      KC_HOSTNAME_ADMIN_URL: https://keycloak.light.local
      
      # 配置上下文地址
      # KEYCLOAK_FRONTEND_URL: https://keycloak.light.local/auth 
      # KC_HTTP_RELATIVE_PATH: /auth
      
      # 禁用HTTPS
      # KC_HOSTNAME_STRICT: false
      # KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      # PROXY_ADDRESS_FORWARDING: true
    command: start --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
    restart: unless-stopped
    # depends_on:
    #   - postgres

  minio:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    container_name: web_minio
    hostname: minio.web
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.172
        aliases:
          - minio.web
    dns:
      - 192.168.137.1
      - 8.8.8.8
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - keycloak.web:172.100.0.170
      - minio.web:172.100.0.172
      - gitlab.web:172.100.0.174
      - gitlab-runner.web:172.100.0.175
      - outline.web:172.100.0.176
      - readeck.web:172.100.0.178
    # ports:
    #   - 9000:9000
    #   - 9001:9001
    expose:
      - 9000
      - 9001
    volumes:
      - //d/docker/develop/web/minio/data:/mnt/data
      - //d/docker/develop/web/minio/conf/config.env:/etc/minio/config.env
    environment:
      MINIO_CONFIG_ENV_FILE: /etc/minio/config.env
    command: ['server', '/data', '--address', ':9000', '--console-address', ':9001']
    restart: unless-stopped

  gitlab:
    image: gitlab/gitlab-ce:17.1.6-ce.0
    privileged: true
    container_name: web_gitlab
    hostname: gitlab.web
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.174
        aliases:
          - gitlab.web
    dns:
      - 192.168.137.1
      - 8.8.8.8
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - keycloak.web:172.100.0.170
      - minio.web:172.100.0.172
      - gitlab.web:172.100.0.174
      - gitlab-runner.web:172.100.0.175
      - outline.web:172.100.0.176
      - readeck.web:172.100.0.178
    ports:
    #   - 80:80 # 注意宿主机和容器内部的端口要一致，否则external_url无法访问
    #   - 443:443
    #   - 22:22
      - 2222:22
    expose:
      - 80
      - 443
      - 22
    environment:
      TZ: Asia/Shanghai
      GITLAB_ROOT_PASSWORD: nJAfvWGS4q1Tw09h=
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['time_zone'] = 'Asia/Shanghai'

        ### 备份配置，这里不能设置自动备份，后面我将介绍怎么在容器外设置自动备份。
        ###! Docs: https://docs.gitlab.com/omnibus/settings/backups.html
        gitlab_rails['backup_keep_time'] = 604800 # 备份保留的时间，单位秒，这里设置为一周

        ### 配置启用、禁用 SSL
        ###! Docs: https://docs.gitlab.com/omnibus/settings/ssl/#configure-https-manually
        # external_url 'http://gitlab.light.local'
        # registry_external_url 'http://gitlab.light.local'
        # letsencrypt['enable'] = false
        # nginx['redirect_http_to_https'] = true
        # nginx['ssl_certificate'] = "/etc/gitlab/ssl/light.local.crt"
        # nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/light.local.key"
        # nginx['ssl_trusted_certificate'] = "/etc/gitlab/ssl/ca.crt"

        ### 配置使用外部 Nginx
        ###! Docs: https://atlassc.net/2022/02/24/self-managed-gitlab-with-docker-compose
        external_url 'https://gitlab.light.local'
        # GitLab 景象中自带一个 Nginx，但是我希望能使用外部的 Nginx 来进行反向代理配置，这样更加灵活，所以在这里禁用掉自带的 Nginx HTTPS 配置，仅使用 80 在主机上提供 HTTP 访问
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        # 强制 https
        # 虽然禁用掉了内置 Nginx 的 HTTPS，我们还是需要在 GitLab 上设置 HTTP 请求转 HTTPS，HTTPS 的反向代理将由外部 Nginx 来完成
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

        ### 配置SSH SSH直接映射到物理机
        gitlab_rails['gitlab_ssh_host'] = 'gitlab.light.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['gitlab_shell_git_timeout'] = 800

        ### 配置使用外部 Pgsql
        ###! Docs: https://docs.gitlab.com/omnibus/settings/database.html
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = "postgresql"
        gitlab_rails['db_encoding'] = "utf-8"
        # gitlab_rails['db_collation'] = nil
        gitlab_rails['db_database'] = "gitlab"
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "gitlab"
        gitlab_rails['db_host'] = "pgsql.basic"
        gitlab_rails['db_port'] = 5432
        gitlab_rails['db_pool'] = 100

        ### 配置使用外部 Redis
        ###! Docs: https://docs.gitlab.com/omnibus/settings/redis.html
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis.basic'
        gitlab_rails['redis_port'] = 6379
        # gitlab_rails['redis_password'] = ''

        ### 配置使用外部认证 keyCloak
        ### https://docs.gitlab.com/ee/administration/auth/oidc.html#configure-keycloak
        gitlab_rails['omniauth_providers'] = [
          {
            name: "openid_connect", # do not change this parameter
            label: "Keycloak", # optional label for login button, defaults to "Openid Connect"
            args: {
              name: "openid_connect",
              scope: ["openid", "profile", "email"],
              response_type: "code",
              issuer:  "https://keycloak.light.local/realms/master",
              client_auth_method: "query",
              discovery: true,
              uid_field: "preferred_username",
              pkce: true,
              client_options: {
                identifier: "Gitlab",
                secret: "5e1b5P0QhYHcWh2gyXutXalrTyEQGzrG",
                redirect_uri: "https://gitlab.light.local/users/auth/openid_connect/callback"
              }
            }
          }
        ]
    volumes:
      - //d/docker/develop/web/gitlab/conf:/etc/gitlab
      - //d/docker/develop/web/gitlab/logs:/var/log/gitlab
      - //d/docker/develop/web/gitlab/data:/var/opt/gitlab
    shm_size: '256m'
    restart: unless-stopped
    # depends_on:
    #   - postgres

  # gitlab-runner:
  #   image: 'gitlab/gitlab-runner:ubi-fips'
  #   container_name: web_gitlab-runner
  #   hostname: gitlab-runner.web
  #   networks:
  #     default: null
  #     develop:
  #       ipv4_address: 172.100.0.175
  #       aliases:
  #         - gitlab-runner.web
  #   dns:
  #     - 192.168.137.1
  #     - 8.8.8.8
  #   extra_hosts:
  #     - mysql.basic:172.100.0.101
  #     - pgsql.basic:172.100.0.106
  #     - redis.basic:172.100.0.111
  #     - influx.basic:172.100.0.116
  #     - mqtt.basic:172.100.0.121
  #     - keycloak.web:172.100.0.170
  #     - minio.web:172.100.0.172
  #     - gitlab.web:172.100.0.174
  #     - gitlab-runner.web:172.100.0.175
  #     - outline.web:172.100.0.176
  #     - readeck.web:172.100.0.178
  #   volumes:
  #     - '/opt/store/gitlab-runner:/etc/gitlab-runner'
  #     # 这个挂载是将宿主机上的docker socket挂载到了容器内，这样容器内执行的docker命令会被宿主机docker daemon最终执行
  #     - '/var/run/docker.sock:/var/run/docker.sock' 
  #   restart: no

  # jenkins:
  #   image: jenkins/jenkins:jdk21
  #   container_name: web_jenkins
  #   hostname: jenkins.web
  #   networks:
  #     default: null
  #     develop:
  #       ipv4_address: 172.100.0.160
  #       aliases:
  #         - jenkins.web
  #   dns:
  #     - 192.168.137.1
  #     - 8.8.8.8
  #   extra_hosts:
  #     - mysql.basic:172.100.0.101
  #     - pgsql.basic:172.100.0.106
  #     - redis.basic:172.100.0.111
  #     - influx.basic:172.100.0.116
  #     - mqtt.basic:172.100.0.121
  #     - keycloak.web:172.100.0.170
  #     - minio.web:172.100.0.172
  #     - gitlab.web:172.100.0.174
  #     - gitlab-runner.web:172.100.0.175
  #     - outline.web:172.100.0.176
  #     - readeck.web:172.100.0.178
  #   # ports:
  #   #   - 8080:8080
  #   #   - 5000:5000
  #   expose:
  #     - 8080
  #     - 5000
  #   user: root
  #   volumes:
  #     - //d/docker/develop/web/jenkins/data/:/var/jenkins_home
  #   restart: no # unless-stopped

  # sonarqube:
  #   image: sonarqube:lts
  #   container_name: web_sonarqube
  #   hostname: sonarqube.web
  #   networks:
  #     default: null
  #     develop:
  #       ipv4_address: 172.100.0.162
  #       aliases:
  #         - sonarqube.web
  #   dns:
  #     - 192.168.137.1
  #     - 8.8.8.8
  #   extra_hosts:
  #     - mysql.basic:172.100.0.101
  #     - pgsql.basic:172.100.0.106
  #     - redis.basic:172.100.0.111
  #     - influx.basic:172.100.0.116
  #     - mqtt.basic:172.100.0.121
  #     - keycloak.web:172.100.0.170
  #     - minio.web:172.100.0.172
  #     - gitlab.web:172.100.0.174
  #     - gitlab-runner.web:172.100.0.175
  #     - outline.web:172.100.0.176
  #     - readeck.web:172.100.0.178
  #   # ports:
  #   #   - 9000:9000
  #   expose:
  #     - 9000
  #   environment:
  #     - SONAR_JDBC_URL=jdbc:postgresql://pgsql.basic:5432/sonar
  #     - SONAR_JDBC_USERNAME=sonar
  #     - SONAR_JDBC_PASSWORD=sonar
  #   volumes:
  #     - //d/docker/develop/web/sonarqube/conf:/opt/sonarqube/conf
  #     - //d/docker/develop/web/sonarqube/data:/opt/sonarqube/data
  #     - //d/docker/develop/web/sonarqube/extensions:/opt/sonarqube/extensions
  #   restart: no # unless-stopped
  #   # depends_on:
  #   #   - postgres

  outline:
    image: outlinewiki/outline:0.80.1
    container_name: web_outline
    hostname: outline.web
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.176
        aliases:
          - outline.web
    dns:
      - 192.168.137.1
      - 8.8.8.8
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - keycloak.web:172.100.0.170
      - minio.web:172.100.0.172
      - gitlab.web:172.100.0.174
      - gitlab-runner.web:172.100.0.175
      - outline.web:172.100.0.176
      - readeck.web:172.100.0.178
    # ports:
    #   - 3000:3000
    expose:
      - 3000
    volumes:
      - //d/docker/develop/web/outline/data:/var/lib/outline/data
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    command: sh -c "sleep 60 && yarn start --env production-ssl-disabled"
    env_file: ./outline/outline.env
    # depends_on:
    #   - postgres
    #   - redis

  readeck:
    image: codeberg.org/readeck/readeck:0.15.3
    container_name: web_readeck
    hostname: readeck.web
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.178
        aliases:
          - readeck.web
    dns:
      - 192.168.137.1
      - 8.8.8.8
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - keycloak.web:172.100.0.170
      - minio.web:172.100.0.172
      - gitlab.web:172.100.0.174
      - gitlab-runner.web:172.100.0.175
      - outline.web:172.100.0.176
      - readeck.web:172.100.0.178
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    volumes:
      - //d/docker/develop/web/readeck/data:/readeck/data
      - //d/docker/develop/web/readeck/conf/config.toml:/readeck/config.toml
    environment:
      # The URL of the instance's database.
      - READECK_DATABASE_SOURCE=postgres://readeck:readeck@pgsql.basic:5432/readeck
      # Defines the application log level. Can be error, warning, info, debug.
      - READECK_LOG_LEVEL=info
      # The IP address on which Readeck listens.
      - READECK_SERVER_HOST=0.0.0.0
      # The TCP port on which Readeck listens. Update container port above to match (right of colon).
      - READECK_SERVER_PORT=8000
      # The URL prefix of Readeck.
      - READECK_SERVER_PREFIX=/
      # A list of hostnames allowed in HTTP requests. Required for reverse proxy configuration.
      - READECK_ALLOWED_HOSTS=readeck.light.local
      # Use the 'X-Forwarded-' headers. Required for reverse proxy configuration.
      - READECK_USE_X_FORWARDED=true
    healthcheck:
      test: ["CMD", "/bin/readeck", "healthcheck", "-config", "config.toml"]
      interval: 30s
      timeout: 2s
      retries: 3
    # depends_on:
    #   - postgres
    #   - redis

networks:
  develop:
    external: true
  proxy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.77.0.0/16

# volumes:
#   keycloak_data:
#   minio_data:
