version: "3"

services:
  caddy:
    image: caddy:2.8
    container_name: web_caddy
    hostname: caddy.web
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.150
        aliases:
          - caddy.web
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - caddy.web:172.100.0.150
      - keycloak.web:172.100.0.152
      - minio.web:172.100.0.154
      - gitlab.web:172.100.0.156
      - outline.web:172.100.0.158
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 2019:2019
    expose:
      - 80
      - 443
      - 2019
    volumes:
      - //d/docker/web/caddy/cert/:/etc/x509/https/
      - //d/docker/web/caddy/site:/srv
      - //d/docker/web/caddy/conf:/config
      - //d/docker/web/caddy/data:/data
    entrypoint: /usr/bin/caddy run --adapter caddyfile --config /config/Caddyfile
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: web_keycloak
    hostname: keycloak.web
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.152
        aliases:
          - keycloak.web
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - caddy.web:172.100.0.150
      - keycloak.web:172.100.0.152
      - minio.web:172.100.0.154
      - gitlab.web:172.100.0.156
      - outline.web:172.100.0.158
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://pgsql.basic:5432/keycloak
      KC_DB_USER: keycloak
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # 外部访问使用的域名端口信息，与 KC_HOSTNAME_URL 二选一
      # KC_HOSTNAME: keycloak.light.local
      # KC_HOSTNAME_PORT: 443
      
      # 外部访问使用的域名地址，解决初始化403问题
      KC_HOSTNAME_URL: https://keycloak.light.local
      KC_HOSTNAME_ADMIN_URL: https://keycloak.light.local
      
      # 配置上下文地址
      # KEYCLOAK_FRONTEND_URL: https://keycloak.light.local/auth 
      # KC_HTTP_RELATIVE_PATH: /auth
      
      # 禁用HTTPS
      # KC_HOSTNAME_STRICT: false
      # KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      # PROXY_ADDRESS_FORWARDING: true
    command: start --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
    restart: unless-stopped
    # depends_on:
    #   - postgres

  minio:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    container_name: web_minio
    hostname: minio.web
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.154
        aliases:
          - minio.web
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - caddy.web:172.100.0.150
      - keycloak.web:172.100.0.152
      - minio.web:172.100.0.154
      - gitlab.web:172.100.0.156
      - outline.web:172.100.0.158
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - 9000
      - 9001
    volumes:
      - //d/docker/web/minio/data:/mnt/data
      - //d/docker/web/minio/conf/config.env:/etc/minio/config.env
    environment:
      MINIO_CONFIG_ENV_FILE: /etc/minio/config.env
    command: ['server', '/data', '--address', ':9000', '--console-address', ':9001']
    restart: unless-stopped

  # gitlab:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: web_outline
    hostname: outline.web
    networks:
      default: null
      develop:
        ipv4_address: 172.100.0.158
        aliases:
          - outline.web
    extra_hosts:
      - mysql.basic:172.100.0.101
      - pgsql.basic:172.100.0.106
      - redis.basic:172.100.0.111
      - influx.basic:172.100.0.116
      - mqtt.basic:172.100.0.121
      - caddy.web:172.100.0.150
      - keycloak.web:172.100.0.152
      - minio.web:172.100.0.154
      - gitlab.web:172.100.0.156
      - outline.web:172.100.0.158
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - //d/docker/web/outline/data:/var/lib/outline/data
    command: sh -c "yarn start --env production-ssl-disabled"
    env_file: //d/docker/web/outline/outline.env
    # depends_on:
    #   - postgres
    #   - redis

networks:
  develop:
    external: true
  proxy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.77.0.0/16

# volumes:
#   caddy_data:
#   minio_data:
